version: "3"
services:
  linux:
    build: 
      # Dockerfile でホスト側のファイルをいじるときには、context を渡す必要がある
      context: ../
      # context を指定した場合は、dockerfile は context の場所からの指定
      dockerfile: ./docker/linux/Dockerfile
    # /bin/init で systemd を起動 （/bin/init は systemd のシンボリックリンク）
    # systemctl（systemd をコントロールするコマンド） start crond.service で cron 起動
    # プロセス ID1 で systemd を起動しないで cron 起動するとエラーが出た
    # 参考：https://tihiro.hatenablog.com/entry/2020/03/20/165252
    command: /sbin/init && sudo systemctl start crond.service
    # コンテナを起動したままにする
    tty: true
    volumes:
    # プロジェクトルート
      - ../:/hanako-san
      # ro(Read-Only)でマウント cgroup（コントロールグループ）
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # ケーパビリティ（root が持つ権限）の追加
    cap_add:
            - SYS_ADMIN
