
build-up: 
	@docker-compose build && docker-compose up -d && docker-compose exec linux bash -c "npm run build"
up:
	@docker-compose up -d
down:
	@docker-compose down
exec-linux:
	@docker-compose exec linux bash